import { Flag } from "./Flag";
import { UserId } from "./UserId"

export interface Timeline {

    title: string;
    adminId: UserId[]; //A collection of users who take control, may read write kick and make people an admin
    tId: string; //auto generated by FireStore

    //events going on a timeline
    events: Flag[];


}